[[pages]]
path = "pages/1_ingredient_list.py"
name = "ğŸ“¦ Ingredient List"
section = "ğŸ¥¬ Ingredients"

[[pages]]
path = "pages/2_add_ingredient.py"
name = "â• Add Ingredient"
section = "ğŸ¥¬ Ingredients"

[[pages]]
path = "pages/3_all_recipes.py"
name = "ğŸ“– All Recipes"
section = "ğŸ½ Recipes"

[[pages]]
path = "pages/4_add_recipe.py"
name = "â• Add Recipe"
section = "ğŸ½ Recipes"
